In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import numpy as np
from sklearn.preprocessing import StandardScaler

In [3]:
dataset1=pd.read_csv("prep.csv",index_col=None)

df2=dataset1

df = pd.get_dummies(df2, drop_first=True)

indep_X=df.drop('classification_yes',axis=1)
dep_Y=df['classification_yes']

In [4]:
df

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [5]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

def LDA(X_train, X_test):
        from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
        lda = LDA(n_components=min(X_train.shape[2], len(np.unique(y_train)) - 1))
        X_train1 = lda.fit_transform(X_train,y_train)
        X_test1 = lda.transform(X_test)
        return X_train1,X_test1
    
def cm_prediction(classifier,X_test1):
        y_pred = classifier.predict(X_test1)
        
        # Making the Confusion Matrix
        from sklearn.metrics import confusion_matrix
        cm = confusion_matrix(y_test, y_pred)
        
        from sklearn.metrics import accuracy_score 
        from sklearn.metrics import classification_report 
        
        Accuracy=accuracy_score(y_test, y_pred)
        report=classification_report(y_test, y_pred)
        
        return  classifier,Accuracy,report,X_test1,y_test,cm

def logistic(X_train1,y_train,X_test1):
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm      
    
def svm_linear(X_train1,y_train,X_test1):              
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def svm_NL(X_train1,y_train,X_test1):             
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm

def Navie(X_train1,y_train,X_test1):       
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm         
    
def knn(X_train1,y_train,X_test1):
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def Decision(X_train1,y_train,X_test1):
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm      


def random(X_train1,y_train,X_test1):
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [6]:
X_train, X_test, y_train, y_test = split_scalar(indep_X,dep_Y)

In [7]:
LDA = LDA(X_train, X_test)

acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

IndexError: tuple index out of range

In [ ]:
LDA

In [ ]:
X_train1,X_test1=LDA

In [ ]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train1,y_train,X_test1)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train1,y_train,X_test1)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train1,y_train,X_test1)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train1,y_train,X_test1)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train1,y_train,X_test1)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train1,y_train,X_test1)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train1,y_train,X_test1)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [ ]:
result
#1

In [ ]:
result
#2

In [ ]:
result
#3

In [ ]:
result
#4

In [ ]:
result
#5

In [ ]:
result
#6

In [ ]:
result
#7

In [ ]:
result
#8

In [ ]:
result
#9

In [ ]:
result
#10